[package]
name = "mao"
version = "0.1.0"
authors = ["Aapuji", "SciDev"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-iterator = "1.4.1"
rand = "0.8.5"
